apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-movie
  namespace: kube-apiserver-minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-movie
  template:
    metadata:
      labels:
        app: test-movie
    spec:
      containers:
      - name: test-movie
        image: 992382663303.dkr.ecr.us-east-1.amazonaws.com/test-movie:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express
  namespace: kube-apiserver-minikube
spec:
  selector:
    app: test-movie
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
